import { describe, expect, it } from 'vitest';
import { createStateFromFen } from '../game';
import { START_FEN } from '../fen';
import { perft } from '../perft';

/**
 * Perft regression anchors for the 9×9 board.
 *
 * The original 8×8 suite was validated against published reference values and
 * an independent engine before the board was expanded; these positions are
 * the same fixtures embedded into 9×9 (extra empty i-file and rank 9), and
 * the counts were generated by this engine at the moment of migration. They
 * no longer prove absolute correctness — they lock the move generator against
 * unintended change.
 */
const POSITIONS: { name: string; fen: string; counts: number[] }[] = [
  {
    name: 'initial position',
    fen: START_FEN,
    counts: [22, 484, 12140, 303821],
  },
  {
    name: 'kiwipete (castling, pins, promotions)',
    fen: '9/r3k2r1/p1ppqpb2/bn2pnp2/3PN4/1p2P4/2N2Q1p1/PPPBBPPP1/R3K2R1 w KQkq - 0 1',
    counts: [50, 2524, 128459],
  },
  {
    name: 'endgame with en passant discoveries',
    fen: '9/9/2p6/3p5/KP5r1/1R3p1k1/9/4P1P2/9 w - - 0 1',
    counts: [14, 243, 3661, 70278],
  },
  {
    name: 'promotion heavy',
    fen: '9/r3k2r1/Pppp1ppp1/1b3nbN1/nP7/BBP1P4/q4N3/Pp1P2PP1/R2Q1RK2 w kq - 0 1',
    counts: [6, 291, 11227],
  },
  {
    name: 'talkchess bug-catcher',
    fen: '9/rnbq1k1r1/pp1Pbppp1/2p6/9/2B6/9/PPP1NnPP1/RNBQK2R1 w KQ - 1 8',
    counts: [42, 1754, 72761],
  },
  {
    name: 'steven edwards position',
    fen: '9/r4rk2/1pp1qppp1/p1np1n3/2b1p1B2/2B1P1b2/P1NP1N3/1PP1QPPP1/R4RK2 w - - 0 10',
    counts: [48, 2541, 115020],
  },
];

describe('perft', () => {
  for (const position of POSITIONS) {
    describe(position.name, () => {
      position.counts.forEach((expected, index) => {
        const depth = index + 1;
        it(`depth ${depth} = ${expected}`, () => {
          expect(perft(createStateFromFen(position.fen), depth)).toBe(expected);
        });
      });
    });
  }
});
